platform :ios, '13.0'

use_frameworks!

inhibit_all_warnings!

target 'app' do
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Storage'
	pod 'OneSignal'
	pod 'RealmSwift'
	pod 'SinchRTC'

	pod 'CryptoSwift'
	pod 'InputBarAccessoryView'
	pod 'IQKeyboardManagerSwift'
	pod 'Kingfisher'
	pod 'MessageKit'
	pod 'NYTPhotoViewer'
	pod 'ProgressHUD'
	pod 'Reachability'
	pod 'RNCryptor-objc'
	pod 'SoundManager'
end
